name: Deploy Service

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://gcr.io/triggermesh/tm:latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Configuration
      env:
        TM_CONFIG: ${{ secrets.TM_CONFIG }}
      run: |
        mkdir $HOME/.tm
        echo "${TM_CONFIG}" > $HOME/.tm/config.json
    - name: Use tm-cli to deploy
      run: |
        /usr/bin/tm deploy --wait
